razzmatazz/csharp-language-server

CHANGELOG.md, src/CSharpLanguageServer/RoslynHelpers.fs
this shows add imports under vscode's quickfix menu.
Not sure though if it doesn't break other clients
=> change CodeAnalysis.AddImport kind to quickfix

src/CSharpLanguageServer/State.fs
1. Replace "%3A" with ":": Some lsp client will escape ":" with "%3A", while the constructor of System.Uri will not unescape "%3A". So unescaping "%3A" manually before passing it to the constructor.
2. Don't concat "file://" manually: Uri("file://" + path) is not equal to Uri(path) because path might contain chars that are interpreted (# and ?). For example, if path is "/mnt/code/c#/project", then the former will treat "/mnt/code/c" as LocalPath and "/project" asFragment.
=> Fix URI parse error

src/CSharpLanguageServer/RoslynHelpers.fs, src/CSharpLanguageServer/Server.fs
This PR is trying to add support for inlay hint. In fact, Roslyn has
already implemented the feature via language service in
https://github.com/dotnet/roslyn/blob/main/src/Features/CSharp/Portable/InlineHints/CSharpInlineTypeHintsService.cs &
https://github.com/dotnet/roslyn/blob/main/src/Features/CSharp/Portable/InlineHints/CSharpInlineParameterNameHintsService.cs.
However, the implementation and the interface, `IInlineHintsService`,
are `internal`, so we can't call the implementation directly (we can't
even get the implementation via
`doc.Project.LanguageServices.GetRequiredService<IInlineHintsService>`).
Hence, this PR rewrites the implementation using F#. Unlike the
implementation in Roslyn, however, this PR always puts type inlay hints
after the identifier and parameter inlay hints …
=> Inlay hint support

src/CSharpLanguageServer/RoslynHelpers.fs, src/CSharpLanguageServer/Server.fs
The `Range` may extend the actual range of the text according to the doc of LSP:
> ... the end position is exclusive. If you want to specify a range
> that contains a line including the line ending character(s) then use
> an end position denoting the start of the next line.
If there is no newline at the end of the last line (which is common for files created by Vistual Studio) and client set the end of Range to the start of the next line of the last line, then csharp-ls will crash because argument is out of the range. On the other hand, we SHOULDN'T trust the value client sent to us.
=> fix: Fix crash if there is no newline at the end of the last line

src/CSharpLanguageServer/Util.fs
1. Add the following missing ClassificationTypeNames -> semantic token maps:
1. Identifier: variable
2. VerbatimStringLiteral: string
2. Fix the following ClassificationTypeNames -> semantic token map since there is no related semantic token:
1. LabelName: label -> variable
Now `ClassificationTypeMap` should cover all possible return values of [Microsoft.CodeAnalysis.CSharp.Classification.ClassificationHelpers.GetClassification](https://github.com/dotnet/roslyn/blob/main/src/Workspaces/CSharp/Portable/Classification/ClassificationHelpers.cs).
=> fix: Semantic token types

src/CSharpLanguageServer/Server.fs
Fixes when solution path retrieval from settings when it's not set.
From vscode I do launch server with `dotnet /.../CSharpLanguageServer.dll --solution my-solution.sln`. And if in vscode settings (it merges global user settings and workspace settings) I have at least one setting that starts with `csharp.` (for example `"csharp.debug.console": "internalConsole"`) then csharp language server ignores solution path from command line and tries to search all projects in cwd. This happens due to when parsing settings from client it sets solution path to `None`.
And looks like official C# vscode extension has lot's of settings that starts with `csharp.`:  https://github.com/dotnet/vscode-csharp/blob/7dc5cbd809aa2d3b304e32c55271a78b021ec29e/package.json#L902 and all of them will be retrieved with …
=> Omit solution path from 'csharp' settings when not set

src/CSharpLanguageServer/RoslynHelpers.fs
Mock HostWorkspaceServices as early as possible to make sure that `document.Project.Solution.Workspace.Services` and `document.Project.Solution.Services.WorkspaceServices` are the same object (to make sure that both of them are mocked).
Fixes #103.
=> fix: Mock HostWorkspaceServices as early as possible

.gitignore, src/CSharpLanguageServer/Server.fs, src/CSharpLanguageServer/State.fs
Resolves #120.
Tested locally using neovim and this seems to work. For decompiled types using , this will require making [csharpls-extended-lsp.nvim](https://github.com/Decodetalkers/csharpls-extended-lsp.nvim) the handler for `textDocument/typeDefinition` e.g.
```lua
require('lspconfig').csharp_ls.setup({
...
handlers = {
["textDocument/definition"] = require('csharpls_extended').handler,
["textDocument/typeDefinition"] = require('csharpls_extended').handler
}
...
})
```
=> Add support for textDocument/typeDefinition

.github/workflows/test.yaml, CHANGELOG.md, global.json, src/CSharpLanguageServer/CSharpLanguageServer.fsproj, src/CSharpLanguageServer/Handlers/CallHierarchy.fs, src/CSharpLanguageServer/Handlers/CodeLens.fs, src/CSharpLanguageServer/Handlers/DocumentSymbol.fs, src/CSharpLanguageServer/Handlers/Initialization.fs, src/CSharpLanguageServer/Handlers/References.fs, src/CSharpLanguageServer/Handlers/Rename.fs, src/CSharpLanguageServer/Handlers/TypeHierarchy.fs, src/CSharpLanguageServer/Lsp/Client.fs, src/CSharpLanguageServer/ProgressReporter.fs, src/CSharpLanguageServer/RoslynHelpers.fs, src/CSharpLanguageServer/State/ServerRequestContext.fs, src/CSharpLanguageServer/State/ServerState.fs
Next PR for gradual integration of https://github.com/tcx4c70/csharp-language-server/commits/rework/ by @tcx4c70
Follows https://github.com/razzmatazz/csharp-language-server/pull/149
=> Integrate refactoring changes (pt. XI)

.github/workflows/build.yaml, .github/workflows/test.yaml, src/CSharpLanguageServer/Lsp/Server.fs, src/CSharpLanguageServer/RoslynHelpers.fs, tests/CSharpLanguageServer.Tests/CSharpLanguageServer.Tests.fsproj, tests/CSharpLanguageServer.Tests/DocumentationTests.fs, tests/CSharpLanguageServer.Tests/InitializationTests.fs, tests/CSharpLanguageServer.Tests/Tooling.fs
This PR adds initial (crude) version of integration tests where the server is initialized and then shut down.
=> Add integration tests

CHANGELOG.md, src/CSharpLanguageServer/Handlers/Completion.fs
CompletionParameters for CompletionService.GetCompletionsAsync have 'ShowItemsFromUnimportedNamespaces' set to true by defualt, which slows down completion.
=> Speed up completion

src/CSharpLanguageServer/Conversions.fs
I was running into an issue with `UriFormat` errors. Reading the dotnet docs, if a relative path is passed into the `Uri` constructor, it throws this error. By adding `UriKind.RelativeOrAbsolute` to the constructor, the errors go away and everything works as expected:
https://learn.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=net-8.0#system-uri-ctor(system-string-system-urikind)
```
lsp-request: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
at System.Uri..ctor(String uriString)
at CSharpLanguageServer.Conversions.Uri.fromPath(String path) in /home/jonny/programming/csharp-language-server/src/CSharpLanguageServer/Conversions.fs:line …
```
=> Add UriKind.RelativeOrAbsolute

CHANGELOG.md, README.md, src/CSharpLanguageServer/CSharpLanguageServer.fsproj, src/CSharpLanguageServer/FormatUtil.fs, src/CSharpLanguageServer/Handlers/DocumentFormatting.fs, src/CSharpLanguageServer/Handlers/DocumentOnTypeFormatting.fs, src/CSharpLanguageServer/Handlers/DocumentRangeFormatting.fs, src/CSharpLanguageServer/Handlers/Workspace.fs, src/CSharpLanguageServer/Program.fs, src/CSharpLanguageServer/State/ServerState.fs, src/CSharpLanguageServer/Types.fs, tests/CSharpLanguageServer.Tests/CSharpLanguageServer.Tests.fsproj, tests/CSharpLanguageServer.Tests/DocumentFormattingTests.fs, tests/CSharpLanguageServer.Tests/TestData/testEditorConfigFormatting/Project/.editorconfig, tests/CSharpLanguageServer.Tests/TestData/testEditorConfigFormatting/Project/Class.cs, tests/CSharpLanguageServer.Tests/TestData/testEditorConfigFormatting/Project/ExpectedFormatting.cs.txt, tests/CSharpLanguageServer.Tests/TestData/testEditorConfigFormatting/Project/Project.csproj, tests/CSharpLanguageServer.Tests/Tooling.fs
Separate branch from dmitry's https://github.com/razzmatazz/csharp-language-server/pull/200
=> Add automatic .editorconfig support (2)

src/CSharpLanguageServer/Handlers/Initialization.fs, src/CSharpLanguageServer/RoslynHelpers.fs
Problem: The server pushes a lot of notifications to the client using "window/showMessage".  All messages are pure informational.
Fix: use "window/logMessage" for all messages that are not errors, Still use "window/showMessage" for errors and exceptions
=> fix(logging): Reduce startup notifications by using "window/logMessage"

CHANGELOG.md, src/CSharpLanguageServer/Conversions.fs, tests/CSharpLanguageServer.Tests/DiagnosticTests.fs
Not all diagnostics will necessarily follow that format so we can just get them from Roslyn.
This also enables things like custom URLS for obsolete warnings.
I'm not sure about how to use the CHANGELOG.md so any guidance there would be appreciated.
=> Get diagnostic url from Roslyn

CHANGELOG.md, src/CSharpLanguageServer/Lsp/Server.fs, src/CSharpLanguageServer/RoslynHelpers.fs, tests/CSharpLanguageServer.Tests/CSharpLanguageServer.Tests.fsproj, tests/CSharpLanguageServer.Tests/InitializationTests.fs, tests/CSharpLanguageServer.Tests/TestData/testMultiTargetProjectLoads/Project/Class.cs, tests/CSharpLanguageServer.Tests/TestData/testMultiTargetProjectLoads/Project/Project.csproj
https://github.com/razzmatazz/csharp-language-server/issues/198
=> Multi-target project support

src/CSharpLanguageServer/RoslynHelpers.fs
The context variable is incorrect and the exception message is not getting printed to the logs. When the log got printed it use the `{exception}` place holder for example:
```log
could not OpenProjectAsync('/path/to/file.csproj'): {exception}
```
=> Fix logging context for exception when projects cannot be opened

CHANGELOG.md, src/CSharpLanguageServer/Handlers/WorkspaceSymbol.fs, src/CSharpLanguageServer/RoslynHelpers.fs
This applies somewhat naive heuristics on the sln files discovered to select the one that has the most projects specified.
Loading projects one-by-one otherwise (when no .sln file is selected) is very slow and this should help it in some cases where the user has not provided a path to .sln file.
=> Attempt to load a solution file even if multiple found

CHANGELOG.md, src/CSharpLanguageServer/RoslynHelpers.fs, tests/CSharpLanguageServer.Tests/InternalTests.fs
Summary:
When using multiple target frameworks in multiple projects. We are currently resolving the latest target framework that exists over all of your projects. The issue with this is the selected target framework may not work with some of the projects.
This resolves the latest target framework that exists in all of your projects. This will give the best framework compatibility.
Test Plan:
Unit test for the existing select latest framework is still there. I have also tested this locally over a project that uses `net8.0` and `net10.0` in some projects.
Ref: #75
=> Use a common target framework from all of your projects

CHANGELOG.md, src/CSharpLanguageServer/CSharpLanguageServer.fsproj, src/CSharpLanguageServer/Diagnostics.fs, src/CSharpLanguageServer/Handlers/Initialization.fs, src/CSharpLanguageServer/Program.fs, src/CSharpLanguageServer/RoslynHelpers.fs, tests/CSharpLanguageServer.Tests/CSharpLanguageServer.Tests.fsproj, tests/CSharpLanguageServer.Tests/DiagnoseCommandTests.fs, tests/CSharpLanguageServer.Tests/TestData/testDiagnoseCommandWorks/Project/Class.cs, tests/CSharpLanguageServer.Tests/TestData/testDiagnoseCommandWorks/Project/Project.csproj
This PR adds `--diagnose` command line option.
=> Add diagnose command
